version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vetcare_db_postgres
    restart: always
    environment:
      POSTGRES_DB: vetcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - vetcare_volume:/var/lib/postgresql/data

volumes:
  vetcare_volume:
